// frontend/src/lib/home/framework/ui/SelfTags.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { Provider } from "react-redux";

import { useTagDispatch, useTagSelector } from "@/lib/home/presenter/tagHook";
import { tagShuffledAction } from "@/lib/home/presenter/tagReducer";
import tagStore from "@/lib/home/presenter/tagStore";

export default function SelfTags() {
  return (
    <Provider store={tagStore}>
      <SelfTagsProvided />
    </Provider>
  );
}

function SelfTagsProvided() {
  const tags = useTagSelector((state) => state.tags);
  const dispatch = useTagDispatch();

  // Initialize with placeholder to prevent flickering
  const [tagsToShow, setTagsToShow] = useState<string[]>([""]);
  const [isTagsVisible, setIsTagsVisible] = useState(false);

  const timer = useRef<NodeJS.Timeout | undefined>(undefined);

  // On mount
  useEffect(() => {
    timer.current = setInterval(() => {
      dispatch(tagShuffledAction());
    }, 4000);

    return () => {
      clearInterval(timer.current);
      timer.current = undefined;
    };
  }, [dispatch]);

  // On tags changed
  useEffect(() => {
    setIsTagsVisible(false);

    setTimeout(() => {
      setTagsToShow(tags);
      setIsTagsVisible(true);
    }, 500);
  }, [tags]);

  return (
    <div
      className={`relative w-full max-w-screen-md transition-opacity duration-500 ${isTagsVisible ? "opacity-100" : "opacity-0"}`}
    >
      <div className="absolute inset-0 bg-gradient-to-r from-transparent via-transparent via-60% to-white" />
      <div className="flex flex-row items-center gap-x-2 overflow-hidden">
        {tagsToShow.map((tag) => (
          <Hashtag key={tag} tag={tag} />
        ))}
      </div>
    </div>
  );
}

function Hashtag(props: { tag: string }) {
  return <span className="text-nowrap text-gray-400"># {props.tag}</span>;
}

// frontend-v2/src/lib/home/framework/ui/SelfTags.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';

	const tagsCollection = [
		'APP',
		'C++',
		'Design Pattern',
		'Docker',
		'Flutter',
		'Go',
		'Java',
		'LINER',
		'Linux',
		'Python',
		'Squid',
		'TypeScript',
		'中央大學',
		'全端',
		'分享',
		'前端',
		'後端',
		'教學',
		'暴肝',
		'知識',
		'碼農',
		'科技',
		'科普',
		'程式設計',
		'資工系',
		'軟體工程',
		'遊戲',
		'魷魚'
	];

	// Initialize with placeholder to prevent flickering
	let showingTags: string[] = $state(['']);
	let isTagsVisible: boolean = $state(false);

	let interval: ReturnType<typeof setInterval> | null = null;

	onMount(() => {
		shuffleTags();
		isTagsVisible = true;

		interval = setInterval(() => {
			isTagsVisible = false;
			setTimeout(() => {
				shuffleTags();
				isTagsVisible = true;
			}, 500);
		}, 4000);
	});

	onDestroy(() => {
		if (interval != null) {
			clearInterval(interval);
			interval = null;
		}
	});

	function shuffleTags() {
		showingTags = [...tagsCollection].sort(() => Math.random() - 0.5);
	}
</script>

<div
	class={`relative w-full max-w-screen-md transition-opacity duration-500 ${isTagsVisible ? 'opacity-100' : 'opacity-0'}`}
>
	<div
		class="absolute inset-0 bg-gradient-to-r from-transparent via-transparent via-60% to-white"
	></div>
	<div class="flex flex-row items-center gap-x-2 overflow-hidden">
		{#each showingTags as tag (tag)}
			<span class="text-nowrap text-gray-400"># {tag}</span>
		{/each}
	</div>
</div>
