// frontend/src/components/layout/footer.tsx
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub, faYoutube } from '@fortawesome/free-brands-svg-icons';
import { faEnvelope } from '@fortawesome/free-solid-svg-icons';
import React from 'react'

type Props = {}

export default function Footer({ }: Props) {
  return (
    <footer className="border-t border-t-slate-200">
      <div className="container flex flex-col md:flex-row md:flex-wrap justify-center items-center py-12 gap-x-6">
        <div className="flex gap-x-4">
        <a href="https://www.youtube.com/@squidspirit16"><FontAwesomeIcon icon={faYoutube} className="h-4 w-4"></FontAwesomeIcon></a>
        <a href="mailto:an920107@gmail.com"><FontAwesomeIcon icon={faEnvelope} className="h-4 w-4"></FontAwesomeIcon></a>
        <a href="https://github.com/an920107/blog"><FontAwesomeIcon icon={faGithub} className="h-4 w-4"></FontAwesomeIcon></a>
        </div>
        <div className="h-2 md:h-6 md:border-s-2 md:border-s-slate-200"></div>
        <p>Copyright © {(new Date()).getFullYear()} SquidSpirit</p>
      </div>
    </footer>
  )
}

// frontend/src/lib/common/framework/ui/Footer.svelte
<script>
	import { Environment } from '$lib/environment';

	const currentYear = new Date().getFullYear();
</script>

<footer class="border-t border-gray-300">
	<div
		class="mx-auto flex max-w-screen-xl flex-col items-center justify-center gap-4 px-4 py-12 text-gray-600 md:flex-row md:px-6"
	>
		<div class="flex flex-row items-center justify-center gap-x-4">
			<a href="https://www.youtube.com/@squidspirit16" target="_blank" aria-label="YouTube Channel">
				<i class="fa-brands fa-youtube size-4" title="YouTube Channel"></i>
			</a>
			<a href="mailto:squid@squidspirit.com" aria-label="Email">
				<i class="fa-solid fa-envelope size-4" title="Email"></i>
			</a>
			<a href="{Environment.APP_BASE_URL}feed.xml" target="_blank" aria-label="RSS Feed">
				<i class="fa-solid fa-square-rss"></i>
			</a>
			<a href="https://git.squidspirit.com/squid/blog" target="_blank" aria-label="Git Repository">
				<i class="fa-brands fa-git-alt size-4" title="Git Repository"></i>
			</a>
		</div>
		<div class="max-md:hidden">
			<div class="h-4 w-0.5 bg-gray-300"></div>
		</div>
		<span class="text-sm">Copyright © {currentYear} SquidSpirit</span>
	</div>
</footer>
